class SuraModel {
  String suraNameArabic;
  String suraNameEnglish;
  String ayasNumber;
  String suraIndex;

  SuraModel({
    required this.suraNameArabic,
    required this.suraNameEnglish,
    required this.ayasNumber,
    required this.suraIndex,
  });

static  List<SuraModel> suras = [
    SuraModel(
      suraNameArabic: "الفاتحه",
      suraNameEnglish: "Al-Fatiha",
      ayasNumber: "7",
      suraIndex: "1",
    ),
    SuraModel(
      suraNameArabic: "البقرة",
      suraNameEnglish: "Al-Baqarah",
      ayasNumber: "286",
      suraIndex: "2",
    ),
    SuraModel(
      suraNameArabic: "آل عمران",
      suraNameEnglish: "Aal-E-Imran",
      ayasNumber: "200",
      suraIndex: "3",
    ),
    SuraModel(
      suraNameArabic: "النساء",
      suraNameEnglish: "An-Nisa'",
      ayasNumber: "176",
      suraIndex: "4",
    ),
    SuraModel(
      suraNameArabic: "المائدة",
      suraNameEnglish: "Al-Ma'idah",
      ayasNumber: "120",
      suraIndex: "5",
    ),
    SuraModel(
      suraNameArabic: "الأنعام",
      suraNameEnglish: "Al-An'am",
      ayasNumber: "165",
      suraIndex: "6",
    ),
    SuraModel(
      suraNameArabic: "الأعراف",
      suraNameEnglish: "Al-A'raf",
      ayasNumber: "206",
      suraIndex: "7",
    ),
    SuraModel(
      suraNameArabic: "الأنفال",
      suraNameEnglish: "Al-Anfal",
      ayasNumber: "75",
      suraIndex: "8",
    ),
    SuraModel(
      suraNameArabic: "التوبة",
      suraNameEnglish: "At-Tawbah",
      ayasNumber: "129",
      suraIndex: "9",
    ),
    SuraModel(
      suraNameArabic: "يونس",
      suraNameEnglish: "Yunus",
      ayasNumber: "109",
      suraIndex: "10",
    ),
    SuraModel(
      suraNameArabic: "هود",
      suraNameEnglish: "Hud",
      ayasNumber: "123",
      suraIndex: "11",
    ),
    SuraModel(
      suraNameArabic: "يوسف",
      suraNameEnglish: "Yusuf",
      ayasNumber: "111",
      suraIndex: "12",
    ),
    SuraModel(
      suraNameArabic: "الرعد",
      suraNameEnglish: "Ar-Ra'd",
      ayasNumber: "43",
      suraIndex: "13",
    ),
    SuraModel(
      suraNameArabic: "إبراهيم",
      suraNameEnglish: "Ibrahim",
      ayasNumber: "52",
      suraIndex: "14",
    ),
    SuraModel(
      suraNameArabic: "الحجر",
      suraNameEnglish: "Al-Hijr",
      ayasNumber: "99",
      suraIndex: "15",
    ),
    SuraModel(
      suraNameArabic: "النحل",
      suraNameEnglish: "An-Nahl",
      ayasNumber: "128",
      suraIndex: "16",
    ),
    SuraModel(
      suraNameArabic: "الإسراء",
      suraNameEnglish: "Al-Isra",
      ayasNumber: "111",
      suraIndex: "17",
    ),
    SuraModel(
      suraNameArabic: "الكهف",
      suraNameEnglish: "Al-Kahf",
      ayasNumber: "110",
      suraIndex: "18",
    ),
    SuraModel(
      suraNameArabic: "مريم",
      suraNameEnglish: "Maryam",
      ayasNumber: "98",
      suraIndex: "19",
    ),
    SuraModel(
      suraNameArabic: "طه",
      suraNameEnglish: "Ta-Ha",
      ayasNumber: "135",
      suraIndex: "20",
    ),
    SuraModel(
      suraNameArabic: "الأنبياء",
      suraNameEnglish: "Al-Anbiya",
      ayasNumber: "112",
      suraIndex: "21",
    ),
    SuraModel(
      suraNameArabic: "الحج",
      suraNameEnglish: "Al-Hajj",
      ayasNumber: "78",
      suraIndex: "22",
    ),
    SuraModel(
      suraNameArabic: "المؤمنون",
      suraNameEnglish: "Al-Mu'minun",
      ayasNumber: "118",
      suraIndex: "23",
    ),
    SuraModel(
      suraNameArabic: "النّور",
      suraNameEnglish: "An-Nur",
      ayasNumber: "64",
      suraIndex: "24",
    ),
    SuraModel(
      suraNameArabic: "الفرقان",
      suraNameEnglish: "Al-Furqan",
      ayasNumber: "77",
      suraIndex: "25",
    ),
    SuraModel(
      suraNameArabic: "الشعراء",
      suraNameEnglish: "Ash-Shu'ara",
      ayasNumber: "227",
      suraIndex: "26",
    ),
    SuraModel(
      suraNameArabic: "النّمل",
      suraNameEnglish: "An-Naml",
      ayasNumber: "93",
      suraIndex: "27",
    ),
    SuraModel(
      suraNameArabic: "القصص",
      suraNameEnglish: "Al-Qasas",
      ayasNumber: "88",
      suraIndex: "28",
    ),
    SuraModel(
      suraNameArabic: "العنكبوت",
      suraNameEnglish: "Al-Ankabut",
      ayasNumber: "69",
      suraIndex: "29",
    ),
    SuraModel(
      suraNameArabic: "الرّوم",
      suraNameEnglish: "Ar-Rum",
      ayasNumber: "60",
      suraIndex: "30",
    ),
    SuraModel(
      suraNameArabic: "لقمان",
      suraNameEnglish: "Luqman",
      ayasNumber: "34",
      suraIndex: "31",
    ),
    SuraModel(
      suraNameArabic: "السجدة",
      suraNameEnglish: "As-Sajda",
      ayasNumber: "30",
      suraIndex: "32",
    ),
    SuraModel(
      suraNameArabic: "الأحزاب",
      suraNameEnglish: "Al-Ahzab",
      ayasNumber: "73",
      suraIndex: "33",
    ),
    SuraModel(
      suraNameArabic: "سبأ",
      suraNameEnglish: "Saba",
      ayasNumber: "54",
      suraIndex: "34",
    ),
    SuraModel(
      suraNameArabic: "فاطر",
      suraNameEnglish: "Fatir",
      ayasNumber: "45",
      suraIndex: "35",
    ),
    SuraModel(
      suraNameArabic: "يس",
      suraNameEnglish: "Ya-Sin",
      ayasNumber: "83",
      suraIndex: "36",
    ),
    SuraModel(
      suraNameArabic: "الصافات",
      suraNameEnglish: "As-Saffat",
      ayasNumber: "182",
      suraIndex: "37",
    ),
    SuraModel(
      suraNameArabic: "ص",
      suraNameEnglish: "Sad",
      ayasNumber: "88",
      suraIndex: "38",
    ),
    SuraModel(
      suraNameArabic: "الزمر",
      suraNameEnglish: "Az-Zumar",
      ayasNumber: "75",
      suraIndex: "39",
    ),
    SuraModel(
      suraNameArabic: "غافر",
      suraNameEnglish: "Ghafir",
      ayasNumber: "85",
      suraIndex: "40",
    ),
    SuraModel(
      suraNameArabic: "فصّلت",
      suraNameEnglish: "Fussilat",
      ayasNumber: "54",
      suraIndex: "41",
    ),
    SuraModel(
      suraNameArabic: "الشورى",
      suraNameEnglish: "Ash-Shura",
      ayasNumber: "53",
      suraIndex: "42",
    ),
    SuraModel(
      suraNameArabic: "الزخرف",
      suraNameEnglish: "Az-Zukhruf",
      ayasNumber: "89",
      suraIndex: "43",
    ),
    SuraModel(
      suraNameArabic: "الدّخان",
      suraNameEnglish: "Ad-Dukhan",
      ayasNumber: "59",
      suraIndex: "44",
    ),
    SuraModel(
      suraNameArabic: "الجاثية",
      suraNameEnglish: "Al-Jathiya",
      ayasNumber: "37",
      suraIndex: "45",
    ),
    SuraModel(
      suraNameArabic: "الأحقاف",
      suraNameEnglish: "Al-Ahqaf",
      ayasNumber: "35",
      suraIndex: "46",
    ),
    SuraModel(
      suraNameArabic: "محمد",
      suraNameEnglish: "Muhammad",
      ayasNumber: "38",
      suraIndex: "47",
    ),
    SuraModel(
      suraNameArabic: "الفتح",
      suraNameEnglish: "Al-Fath",
      ayasNumber: "29",
      suraIndex: "48",
    ),
    SuraModel(
      suraNameArabic: "الحجرات",
      suraNameEnglish: "Al-Hujurat",
      ayasNumber: "18",
      suraIndex: "49",
    ),
    SuraModel(
      suraNameArabic: "ق",
      suraNameEnglish: "Qaf",
      ayasNumber: "45",
      suraIndex: "50",
    ),
    SuraModel(
      suraNameArabic: "الذاريات",
      suraNameEnglish: "Adh-Dhariyat",
      ayasNumber: "60",
      suraIndex: "51",
    ),
    SuraModel(
      suraNameArabic: "الطور",
      suraNameEnglish: "At-Tur",
      ayasNumber: "49",
      suraIndex: "52",
    ),
    SuraModel(
      suraNameArabic: "النجم",
      suraNameEnglish: "An-Najm",
      ayasNumber: "62",
      suraIndex: "53",
    ),
    SuraModel(
      suraNameArabic: "القمر",
      suraNameEnglish: "Al-Qamar",
      ayasNumber: "55",
      suraIndex: "54",
    ),
    SuraModel(
      suraNameArabic: "الرحمن",
      suraNameEnglish: "Ar-Rahman",
      ayasNumber: "78",
      suraIndex: "55",
    ),
    SuraModel(
      suraNameArabic: "الواقعة",
      suraNameEnglish: "Al-Waqi'a",
      ayasNumber: "96",
      suraIndex: "56",
    ),
    SuraModel(
      suraNameArabic: "الحديد",
      suraNameEnglish: "Al-Hadid",
      ayasNumber: "29",
      suraIndex: "57",
    ),
    SuraModel(
      suraNameArabic: "المجادلة",
      suraNameEnglish: "Al-Mujadila",
      ayasNumber: "22",
      suraIndex: "58",
    ),
    SuraModel(
      suraNameArabic: "الحشر",
      suraNameEnglish: "Al-Hashr",
      ayasNumber: "24",
      suraIndex: "59",
    ),
    SuraModel(
      suraNameArabic: "الممتحنة",
      suraNameEnglish: "Al-Mumtahina",
      ayasNumber: "13",
      suraIndex: "60",
    ),
    SuraModel(
      suraNameArabic: "الصف",
      suraNameEnglish: "As-Saff",
      ayasNumber: "14",
      suraIndex: "61",
    ),
    SuraModel(
      suraNameArabic: "الجمعة",
      suraNameEnglish: "Al-Jumu'a",
      ayasNumber: "11",
      suraIndex: "62",
    ),
    SuraModel(
      suraNameArabic: "المنافقون",
      suraNameEnglish: "Al-Munafiqun",
      ayasNumber: "11",
      suraIndex: "63",
    ),
    SuraModel(
      suraNameArabic: "التغابن",
      suraNameEnglish: "At-Taghabun",
      ayasNumber: "18",
      suraIndex: "64",
    ),
    SuraModel(
      suraNameArabic: "الطلاق",
      suraNameEnglish: "At-Talaq",
      ayasNumber: "12",
      suraIndex: "65",
    ),
    SuraModel(
      suraNameArabic: "التحريم",
      suraNameEnglish: "At-Tahrim",
      ayasNumber: "12",
      suraIndex: "66",
    ),
    SuraModel(
      suraNameArabic: "الملك",
      suraNameEnglish: "Al-Mulk",
      ayasNumber: "30",
      suraIndex: "67",
    ),
    SuraModel(
      suraNameArabic: "القلم",
      suraNameEnglish: "Al-Qalam",
      ayasNumber: "52",
      suraIndex: "68",
    ),
    SuraModel(
      suraNameArabic: "الحاقة",
      suraNameEnglish: "Al-Haqqah",
      ayasNumber: "52",
      suraIndex: "69",
    ),
    SuraModel(
      suraNameArabic: "المعارج",
      suraNameEnglish: "Al-Ma'arij",
      ayasNumber: "44",
      suraIndex: "70",
    ),
    SuraModel(
      suraNameArabic: "نوح",
      suraNameEnglish: "Nuh",
      ayasNumber: "28",
      suraIndex: "71",
    ),
    SuraModel(
      suraNameArabic: "الجن",
      suraNameEnglish: "Al-Jinn",
      ayasNumber: "28",
      suraIndex: "72",
    ),
    SuraModel(
      suraNameArabic: "المزّمّل",
      suraNameEnglish: "Al-Muzzammil",
      ayasNumber: "20",
      suraIndex: "73",
    ),
    SuraModel(
      suraNameArabic: "المدّثر",
      suraNameEnglish: "Al-Muddathir",
      ayasNumber: "56",
      suraIndex: "74",
    ),
    SuraModel(
      suraNameArabic: "القيامة",
      suraNameEnglish: "Al-Qiyamah",
      ayasNumber: "40",
      suraIndex: "75",
    ),
    SuraModel(
      suraNameArabic: "الإنسان",
      suraNameEnglish: "Al-Insan",
      ayasNumber: "31",
      suraIndex: "76",
    ),
    SuraModel(
      suraNameArabic: "المرسلات",
      suraNameEnglish: "Al-Mursalat",
      ayasNumber: "50",
      suraIndex: "77",
    ),
    SuraModel(
      suraNameArabic: "النبأ",
      suraNameEnglish: "An-Naba'",
      ayasNumber: "40",
      suraIndex: "78",
    ),
    SuraModel(
      suraNameArabic: "النازعات",
      suraNameEnglish: "An-Nazi'at",
      ayasNumber: "46",
      suraIndex: "79",
    ),
    SuraModel(
      suraNameArabic: "عبس",
      suraNameEnglish: "Abasa",
      ayasNumber: "42",
      suraIndex: "80",
    ),
    SuraModel(
      suraNameArabic: "التكوير",
      suraNameEnglish: "At-Takwir",
      ayasNumber: "29",
      suraIndex: "81",
    ),
    SuraModel(
      suraNameArabic: "الإنفطار",
      suraNameEnglish: "Al-Infitar",
      ayasNumber: "19",
      suraIndex: "82",
    ),
    SuraModel(
      suraNameArabic: "المطفّفين",
      suraNameEnglish: "Al-Mutaffifin",
      ayasNumber: "36",
      suraIndex: "83",
    ),
    SuraModel(
      suraNameArabic: "الإنشقاق",
      suraNameEnglish: "Al-Inshiqaq",
      ayasNumber: "25",
      suraIndex: "84",
    ),
    SuraModel(
      suraNameArabic: "البروج",
      suraNameEnglish: "Al-Buruj",
      ayasNumber: "22",
      suraIndex: "85",
    ),
    SuraModel(
      suraNameArabic: "الطارق",
      suraNameEnglish: "At-Tariq",
      ayasNumber: "17",
      suraIndex: "86",
    ),
    SuraModel(
      suraNameArabic: "الأعلى",
      suraNameEnglish: "Al-A'la",
      ayasNumber: "19",
      suraIndex: "87",
    ),
    SuraModel(
      suraNameArabic: "الغاشية",
      suraNameEnglish: "Al-Ghashiyah",
      ayasNumber: "26",
      suraIndex: "88",
    ),
    SuraModel(
      suraNameArabic: "الفجر",
      suraNameEnglish: "Al-Fajr",
      ayasNumber: "30",
      suraIndex: "89",
    ),
    SuraModel(
      suraNameArabic: "البلد",
      suraNameEnglish: "Al-Balad",
      ayasNumber: "20",
      suraIndex: "90",
    ),
    SuraModel(
      suraNameArabic: "الشمس",
      suraNameEnglish: "Ash-Shams",
      ayasNumber: "15",
      suraIndex: "91",
    ),
    SuraModel(
      suraNameArabic: "الليل",
      suraNameEnglish: "Al-Lail",
      ayasNumber: "21",
      suraIndex: "92",
    ),
    SuraModel(
      suraNameArabic: "الضحى",
      suraNameEnglish: "Ad-Duha",
      ayasNumber: "11",
      suraIndex: "93",
    ),
    SuraModel(
      suraNameArabic: "الشرح",
      suraNameEnglish: "Ash-Sharh",
      ayasNumber: "8",
      suraIndex: "94",
    ),
    SuraModel(
      suraNameArabic: "التين",
      suraNameEnglish: "At-Tin",
      ayasNumber: "8",
      suraIndex: "95",
    ),
    SuraModel(
      suraNameArabic: "العلق",
      suraNameEnglish: "Al-Alaq",
      ayasNumber: "19",
      suraIndex: "96",
    ),
    SuraModel(
      suraNameArabic: "القدر",
      suraNameEnglish: "Al-Qadr",
      ayasNumber: "5",
      suraIndex: "97",
    ),
    SuraModel(
      suraNameArabic: "البينة",
      suraNameEnglish: "Al-Bayyina",
      ayasNumber: "8",
      suraIndex: "98",
    ),
    SuraModel(
      suraNameArabic: "الزلزلة",
      suraNameEnglish: "Az-Zalzalah",
      ayasNumber: "8",
      suraIndex: "99",
    ),
    SuraModel(
      suraNameArabic: "العاديات",
      suraNameEnglish: "Al-Adiyat",
      ayasNumber: "11",
      suraIndex: "100",
    ),
    SuraModel(
      suraNameArabic: "القارعة",
      suraNameEnglish: "Al-Qari'a",
      ayasNumber: "11",
      suraIndex: "101",
    ),
    SuraModel(
      suraNameArabic: "التكاثر",
      suraNameEnglish: "At-Takathur",
      ayasNumber: "8",
      suraIndex: "102",
    ),
    SuraModel(
      suraNameArabic: "العصر",
      suraNameEnglish: "Al-Asr",
      ayasNumber: "3",
      suraIndex: "103",
    ),
    SuraModel(
      suraNameArabic: "الهمزة",
      suraNameEnglish: "Al-Humazah",
      ayasNumber: "9",
      suraIndex: "104",
    ),
    SuraModel(
      suraNameArabic: "الفيل",
      suraNameEnglish: "Al-Fil",
      ayasNumber: "5",
      suraIndex: "105",
    ),
    SuraModel(
      suraNameArabic: "قريش",
      suraNameEnglish: "Quraysh",
      ayasNumber: "4",
      suraIndex: "106",
    ),
    SuraModel(
      suraNameArabic: "الماعون",
      suraNameEnglish: "Al-Ma'un",
      ayasNumber: "7",
      suraIndex: "107",
    ),
    SuraModel(
      suraNameArabic: "الكوثر",
      suraNameEnglish: "Al-Kawthar",
      ayasNumber: "3",
      suraIndex: "108",
    ),
    SuraModel(
      suraNameArabic: "الكافرون",
      suraNameEnglish: "Al-Kafirun",
      ayasNumber: "6",
      suraIndex: "109",
    ),
    SuraModel(
      suraNameArabic: "النصر",
      suraNameEnglish: "An-Nasr",
      ayasNumber: "3",
      suraIndex: "110",
    ),
    SuraModel(
      suraNameArabic: "المسد",
      suraNameEnglish: "Al-Masad",
      ayasNumber: "5",
      suraIndex: "111",
    ),
    SuraModel(
      suraNameArabic: "الإخلاص",
      suraNameEnglish: "Al-Ikhlas",
      ayasNumber: "4",
      suraIndex: "112",
    ),
    SuraModel(
      suraNameArabic: "الفلق",
      suraNameEnglish: "Al-Falaq",
      ayasNumber: "5",
      suraIndex: "113",
    ),
    SuraModel(
      suraNameArabic: "الناس",
      suraNameEnglish: "An-Nas",
      ayasNumber: "6",
      suraIndex: "114",
    ),
  ];
}
